GET http://localhost:3000/transactions/

###

GET http://localhost:3000/transactions/d39317ec-641b-4627-b8a5-ec6a8c447c77

###

POST http://localhost:3000/transactions/
Content-Type: application/json

{
    "amount": "100",
    "account_id": "1"
}

###

PATCH http://localhost:3000/transactions/d39317ec-641b-4627-b8a5-ec6a8c447c77
Content-Type: application/json

{
    "amount": "2099"
}

###

DELETE http://localhost:3000/transactions/d39317ec-641b-4627-b8a5-ec6a8c447c77
