GET http://localhost:3000/transactions/

###

GET http://localhost:3000/transactions/03a52920-0032-4eed-8055-ae9d334c5a55

###

POST http://localhost:3000/transactions/
Content-Type: application/json

{
    "amount": "100",
    "account_id": "1"
}

###

PATCH http://localhost:3000/transactions/548d07b2-57ad-4b5f-83fd-6bb42f3e113f
Content-Type: application/json

{
    "amount": "2099"
}

###

DELETE http://localhost:3000/transactions/20cdd924-2f06-4ffb-a358-11ecd0a9a27d
