version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.app
    container_name: app
    #init: true
    entrypoint: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules

  db:
    build: 
      context: .
      dockerfile: ./Dockerfile.database    
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./.dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fin
