apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio3-deployment
spec:
  selector:
    matchLabels:
      app: desafio3
  template:
    metadata:
      labels:
        app: desafio3
    spec:
      containers:
      - name: desafio3
        image: nginx:latest
        ports:
        - containerPort: 80