# cluster-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1beta2 
nodes:
- role: worker
- role: worker
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP