GET http://localhost:3000/api/

###

GET http://localhost:3000/teste/dfdfdf

###

GET http://localhost:3000/orders/

###

GET http://localhost:3000/orders/a0b5ff9c-7238-4d2f-ae48-fc96be71c80d

###

POST http://localhost:3000/orders/
Content-Type: application/json

{
    "amount": "100"
}

###

PATCH http://localhost:3000/orders/a0b5ff9c-7238-4d2f-ae48-fc96be71c80d
Content-Type: application/json

{
    "amount": "2099",
    "status": "paid"
}

###

DELETE http://localhost:3000/orders/a0b5ff9c-7238-4d2f-ae48-fc96be71c80d
