version: '3'

services:
  app:
    build: .
    container_name: app
    entrypoint: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs-api:/home/node/app
      - /home/node/app/node_modules

  db:
    build: ./.docker/mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fin
